### DISCUSSION TITLE
Q: How to use this action for caching .NET SDK image?

### DISCUSSION THREAD

**Discussion by vitalykarasik** [ScribeMD/docker-cache#822] [Q&A]
I'm using 'mcr.microsoft.com/dotnet/sdk:6.0' image for running .NET tests. If I understand right, this action should be able to cache this image, but I don't see it happening.

I used these params:

```
    - name: Cache Docker images
      uses: ScribeMD/docker-cache@0.5.0
      with:
        key: docker-${{ runner.os }}-${{ hashFiles('**/Dockerfile') }}   
```
