### ISSUE TITLE
Preexisting Docker images are only listed after pull, so nothing is cached

### ISSUE THREAD

**Issue by lars-reimann** [ScribeMD/docker-cache#292]
I want to use this action to cache the [MegaLinter](https://github.com/oxsecurity/megalinter) Docker image to speed up my CI pipeline, which seems to be exactly what this action was designed for.

I've now added another step to my `megalinter.yml` workflow that uses `docker-cache` prior to the MegaLinter step, as instructed by the README:

```yml
# ...

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      # Git Checkout
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      # Cache MegaLinter image
      - name: Cache Docker images
        uses: ScribeMD/docker-cache@0.2.6
        with:
          key: docker-${{ runner.os }}-${{ hashFiles('.github/workflows/megalinter.yml') }}

      # MegaLinter
      - name: MegaLinter
        id: ml
        uses: oxsecurity/megalinter@v6.13.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # ...
```

However, when I now run this workflow, the pull of the MegaLinter image is lifted up and run first:

![image](https://user-images.githubusercontent.com/2501322/203556772-f6eae3e8-c1da-4664-a898-12d985dca5f0.png)

Only afterwards does `docker-cache` retrieve the list of pre-installed Docker images, which now also includes MegaLinter:

![image](https://user-images.githubusercontent.com/2501322/203557013-0da6d451-558d-42cc-a44c-bf6a66e116b4.png)

Because of this, the post-action does not find any difference between the Docker images before and after the workflow is run and nothing is cached:

![image](https://user-images.githubusercontent.com/2501322/203557286-016367ab-e2f1-4e0a-96d3-9d2e698a9c66.png)

I'm a little confused by this behavior since the documentation of GitHub actions clearly says that ["Steps are executed in order and are dependent on each other."](https://docs.github.com/en/actions/learn-github-actions/understanding-github-actions#jobs). Because of I'm not sure whether this is an issue with my configuration, MegaLinter, `docker-cache`, or some "optimization" applied by GitHub Actions, so sorry if this is unrelated to `docker-cache`.
