### ISSUE TITLE
Cannot use output from a previous step in key

### ISSUE THREAD

**Issue by marc-hb** [ScribeMD/docker-cache#305]
I'm successfully fetching the digest of the `latest` image (before downloading the actual image) with `docker manifest inspect ghcr.io/zephyrproject-rtos/ci:latest -v | jq -r '.[0].Descriptor.digest'` and I'm (naively?) trying to use it in the `key`.

I first tried `set-output` as documented here: https://github.com/marketplace/actions/cache#creating-a-cache-key
```yaml
      - name: get digest of latest ghcr.io/zephyrproject-rtos/ci
        id: latest-zephyr-img
        run: |
          docker manifest inspect ghcr.io/zephyrproject-rtos/ci:latest -v | jq -r '.[0].Descriptor.digest' | tee latest-img
          echo "::set-output name=date::$(cat latest-img)"

      - name: Cache Docker images
        uses: ScribeMD/docker-cache@0.2.6
        with: # can't get digest :-(
          key: zephyr-build-img-${{ steps.latest-zephyr-img.digest }}
```

But the value looks empty.

Then Github informed me that `set-output` is deprecated. So I followed the new documentation and switched to GITHUB_OUTPUT: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

```yaml

      - name: get digest of latest ghcr.io/zephyrproject-rtos/ci
        id: latest-zephyr-img
        run: |
          docker manifest inspect ghcr.io/zephyrproject-rtos/ci:latest -v | jq -r '.[0].Descriptor.digest' | tee latest-img
          printf 'digest=%s\n' "$(cat latest-img)" >> "${GITHUB_OUTPUT}"
```

Still empty: https://github.com/thesofproject/sof/actions/runs/3851840976/jobs/6563431229

Is this problem specific to docker-cache?
