### ISSUE TITLE
Is it possible to cache the image locally built?

### ISSUE THREAD

**Issue by yegor256** [ScribeMD/docker-cache#817]
I'm doing this:

```
jobs:
  make:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@master
      - uses: ScribeMD/docker-cache@0.5.0
        with:
          key: docker-${{ runner.os }}-${{ hashFiles('Dockerfile') }}
      - run: docker build . -t cam
      - run: docker run --rm cam make test
```

I intend to build the image only once, unless the `Dockerfile` is changed. However, this approach doesn't work: the `docker build` starts from scratch, even though your plugin finishes with this:

```
...
docker load --input ~/.docker-images.tar
Loaded image: cam:latest
```

Full log is here: https://github.com/yegor256/cam/actions/runs/8498131819/job/23277521845
